### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jailupatel007** [echonox/cordova-plugin-snackbar#7]
How to Solve ?

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-snackbar@2.1.4" via npm Installing "cordova-plugin-snackbar" at "2.1.4" for android Failed to install 'cordova-plugin-snackbar':Error: Unable to graft xml at selector "/manifest/application/activity[@android:name='MainActivity']" from "/tmp/gimlet/26963800/2658080/www_android/project/AndroidManifest.xml" during config install at ConfigFile_graft_child [as graft_child] (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:120:19) at PlatformMunger_apply_file_munge [as apply_file_munge] (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:86:34) at munge_helper (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:265:14) at PlatformMunger.add_plugin_changes (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:179:12) at /tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/cordova-common/src/PluginManager.js:126:25 at _fulfilled (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/q/q.js:834:54) at self.promiseDispatch.done (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/q/q.js:863:30) at Promise.promise.promiseDispatch (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/q/q.js:796:13) at /tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/q/q.js:857:14 at runSingle (/tmp/gimlet/26963800/2658080/www_android/project/cordova/node_modules/q/q.js:137:13) Unable to graft xml at selector "/manifest/application/activity[@android:name='MainActivity']" from "/tmp/gimlet/26963800/2658080/www_android/project/AndroidManifest.xml" during config install - You can fix this here

**Comment by angjelkom** [comment]
@jailupatel007 what cordova version do you use?

**Comment by angjelkom** [comment]
Closing issue because of inactivity
